name: Build and Push Docker Image

# Trigger the workflow on every push to the dev branch
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository for source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx (for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Create firebase.json from secret
      - name: Create firebase.json file from secret
        run: |
          echo "${{ secrets.FIREBASE_JSON }}" > firebase.json

      # Step 5: Build the Docker image (use the correct context and Dockerfile path)
      - name: Build and tag Docker image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:latest -f TeamoWeb.API/Dockerfile .

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:latest
